# Generated by Django 5.0.6 on 2024-05-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTanques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
