# Generated by Django 5.0.6 on 2024-05-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTanques', '0002_tank_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
