# Generated by Django 5.0.6 on 2024-05-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTanques', '0003_alter_tank_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
